development:
  adapter: postgresql
  encoding: unicode
  database: better_hire_tdd_development
  pool: 5
  username: jefcurtis 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: better_hire_tdd_test
  pool: 5
  username: jefcurtis
  password: